In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [12]:
dataset=pd.read_csv("DiseasePrediction.csv")
dataset

Disease             Symptom_1  \
0                            Fungal infection               itching   
1                            Fungal infection             skin_rash   
2                            Fungal infection               itching   
3                            Fungal infection               itching   
4                            Fungal infection               itching   
...                                       ...                   ...   
4915  (vertigo) Paroymsal  Positional Vertigo              vomiting   
4916                                     Acne             skin_rash   
4917                  Urinary tract infection   burning_micturition   
4918                                Psoriasis             skin_rash   
4919                                 Impetigo             skin_rash   

                  Symptom_2              Symptom_3                  Symptom_4  \
0                 skin_rash   nodal_skin_eruptions        dischromic _patches   
1      nodal_skin_eruptions    dischromic _patches                        NaN   
2      nodal_skin_eruptions    dischromic _patches                        NaN   
3                 skin_rash    dischromic _patches                        NaN   
4                 skin_rash   nodal_skin_eruptions                        NaN   
...                     ...                    ...                        ...   
4915               headache                 nausea         spinning_movements   
4916     pus_filled_pimples             blackheads                   scurring   
4917     bladder_discomfort    foul_smell_of urine   continuous_feel_of_urine   
4918             joint_pain           skin_peeling        silver_like_dusting   
4919             high_fever                blister       red_sore_around_nose   

                  Symptom_5            Symptom_6 Symptom_7 Symptom_8  \
0                       NaN                  NaN       NaN       NaN   
1                       NaN                  NaN       NaN       NaN   
2                       NaN                  NaN       NaN       NaN   
3                       NaN                  NaN       NaN       NaN   
4                       NaN                  NaN       NaN       NaN   
...                     ...                  ...       ...       ...   
4915        loss_of_balance         unsteadiness       NaN       NaN   
4916                    NaN                  NaN       NaN       NaN   
4917                    NaN                  NaN       NaN       NaN   
4918   small_dents_in_nails   inflammatory_nails       NaN       NaN   
4919      yellow_crust_ooze                  NaN       NaN       NaN   

     Symptom_9 Symptom_10 Symptom_11 Symptom_12 Symptom_13 Symptom_14  \
0          NaN        NaN        NaN        NaN        NaN        NaN   
1          NaN        NaN        NaN        NaN        NaN        NaN   
2          NaN        NaN        NaN        NaN        NaN        NaN   
3          NaN        NaN        NaN        NaN        NaN        NaN   
4          NaN        NaN        NaN        NaN        NaN        NaN   
...        ...        ...        ...        ...        ...        ...   
4915       NaN        NaN        NaN        NaN        NaN        NaN   
4916       NaN        NaN        NaN        NaN        NaN        NaN   
4917       NaN        NaN        NaN        NaN        NaN        NaN   
4918       NaN        NaN        NaN        NaN        NaN        NaN   
4919       NaN        NaN        NaN        NaN        NaN        NaN   

     Symptom_15 Symptom_16 Symptom_17  
0           NaN        NaN        NaN  
1           NaN        NaN        NaN  
2           NaN        NaN        NaN  
3           NaN        NaN        NaN  
4           NaN        NaN        NaN  
...         ...        ...        ...  
4915        NaN        NaN        NaN  
4916        NaN        NaN        NaN  
4917        NaN        NaN        NaN  
4918        NaN        NaN        NaN  
4919        NaN        NaN    

In [13]:
dataset['Disease'].unique()

array(['Fungal infection', 'Allergy', 'GERD', 'Chronic cholestasis',
       'Drug Reaction', 'Peptic ulcer diseae', 'AIDS', 'Diabetes ',
       'Gastroenteritis', 'Bronchial Asthma', 'Hypertension ', 'Migraine',
       'Cervical spondylosis', 'Paralysis (brain hemorrhage)', 'Jaundice',
       'Malaria', 'Chicken pox', 'Dengue', 'Typhoid', 'hepatitis A',
       'Hepatitis B', 'Hepatitis C', 'Hepatitis D', 'Hepatitis E',
       'Alcoholic hepatitis', 'Tuberculosis', 'Common Cold', 'Pneumonia',
       'Dimorphic hemmorhoids(piles)', 'Heart attack', 'Varicose veins',
       'Hypothyroidism', 'Hyperthyroidism', 'Hypoglycemia',
       'Osteoarthristis', 'Arthritis',
       '(vertigo) Paroymsal  Positional Vertigo', 'Acne',
       'Urinary tract infection', 'Psoriasis', 'Impetigo'], dtype=object)

In [21]:
len(dataset['Disease'].unique())

41

In [11]:
len(dataset)

4920

In [28]:
#convert categorical data into numeric data
from sklearn.preprocessing import LabelEncoder

In [29]:
# Initialize LabelEncoder
disease=LabelEncoder()

dataset['Disease']=disease.fit_transform(dataset['Disease'])
dataset

Disease             Symptom_1              Symptom_2  \
0          15               itching              skin_rash   
1          15             skin_rash   nodal_skin_eruptions   
2          15               itching   nodal_skin_eruptions   
3          15               itching              skin_rash   
4          15               itching              skin_rash   
...       ...                   ...                    ...   
4915        0              vomiting               headache   
4916        2             skin_rash     pus_filled_pimples   
4917       38   burning_micturition     bladder_discomfort   
4918       35             skin_rash             joint_pain   
4919       27             skin_rash             high_fever   

                  Symptom_3                  Symptom_4              Symptom_5  \
0      nodal_skin_eruptions        dischromic _patches                    NaN   
1       dischromic _patches                        NaN                    NaN   
2       dischromic _patches                        NaN                    NaN   
3       dischromic _patches                        NaN                    NaN   
4      nodal_skin_eruptions                        NaN                    NaN   
...                     ...                        ...                    ...   
4915                 nausea         spinning_movements        loss_of_balance   
4916             blackheads                   scurring                    NaN   
4917    foul_smell_of urine   continuous_feel_of_urine                    NaN   
4918           skin_peeling        silver_like_dusting   small_dents_in_nails   
4919                blister       red_sore_around_nose      yellow_crust_ooze   

                Symptom_6 Symptom_7 Symptom_8 Symptom_9 Symptom_10 Symptom_11  \
0                     NaN       NaN       NaN       NaN        NaN        NaN   
1                     NaN       NaN       NaN       NaN        NaN        NaN   
2                     NaN       NaN       NaN       NaN        NaN        NaN   
3                     NaN       NaN       NaN       NaN        NaN        NaN   
4                     NaN       NaN       NaN       NaN        NaN        NaN   
...                   ...       ...       ...       ...        ...        ...   
4915         unsteadiness       NaN       NaN       NaN        NaN        NaN   
4916                  NaN       NaN       NaN       NaN        NaN        NaN   
4917                  NaN       NaN       NaN       NaN        NaN        NaN   
4918   inflammatory_nails       NaN       NaN       NaN        NaN        NaN   
4919                  NaN       NaN       NaN       NaN        NaN        NaN   

     Symptom_12 Symptom_13 Symptom_14 Symptom_15 Symptom_16 Symptom_17  
0           NaN        NaN        NaN        NaN        NaN        NaN  
1           NaN        NaN        NaN        NaN        NaN        NaN  
2           NaN        NaN        NaN        NaN        NaN        NaN  
3           NaN        NaN        NaN        NaN        NaN        NaN  
4           NaN        NaN        NaN        NaN        NaN        NaN  
...         ...        ...        ...        ...        ...        ...  
4915        NaN        NaN        NaN        NaN        NaN        NaN  
4916        NaN        NaN        NaN        NaN        NaN        NaN  
4917        NaN        NaN        NaN        NaN        NaN        NaN  
4918        NaN        NaN        NaN        NaN        NaN        NaN  
4919        NaN        NaN        NaN        NaN        NaN        NaN  

[4920 rows x 18 columns]

In [32]:
from sklearn.preprocessing import LabelEncoder

# Initialize LabelEncoder
symptoms_encoder = LabelEncoder()

# List of symptom columns
symptom_cols = ["Symptom_1", "Symptom_2", "Symptom_3", "Symptom_4", "Symptom_5",
                "Symptom_6", "Symptom_7", "Symptom_8", "Symptom_9", "Symptom_10",
                "Symptom_11", "Symptom_12", "Symptom_13", "Symptom_14", "Symptom_15",
                "Symptom_16", "Symptom_17"]

# Apply Label Encoding to each symptom column
for col in symptom_cols:
    dataset[col] = symptoms_encoder.fit_transform(dataset[col])
dataset


Disease  Symptom_1  Symptom_2  Symptom_3  Symptom_4  Symptom_5  \
0          15         33         35         35         11         38   
1          15         24         27         18         50         38   
2          15         33         27         18         50         38   
3          15         33         35         18         50         38   
4          15         33         35         35         50         38   
...       ...        ...        ...        ...        ...        ...   
4915        0         28         17         33         38         22   
4916        2         24         31          3         35         38   
4917       38          4          4         22          7         38   
4918       35         24         20         42         36         27   
4919       27         24         18          4         33         35   

      Symptom_6  Symptom_7  Symptom_8  Symptom_9  Symptom_10  Symptom_11  \
0            32         26         21         22          21          18   
1            32         26         21         22          21          18   
2            32         26         21         22          21          18   
3            32         26         21         22          21          18   
4            32         26         21         22          21          18   
...         ...        ...        ...        ...         ...         ...   
4915         29         26         21         22          21          18   
4916         32         26         21         22          21          18   
4917         32         26         21         22          21          18   
4918         15         26         21         22          21          18   
4919         32         26         21         22          21          18   

      Symptom_12  Symptom_13  Symptom_14  Symptom_15  Symptom_16  Symptom_17  
0             11           8           4           3           3           1  
1             11           8           4           3           3           1  
2             11           8           4           3           3           1  
3             11           8           4           3           3           1  
4             11           8           4           3           3           1  
...          ...         ...         ...         ...         ...         ...  
4915          11           8           4           3           3           1  
4916          11           8           4           3           3           1  
4917          11           8           4           3           3           1  
4918          11           8           4           3           3           1  
4919          11           8           4           3           3           1  

[4920 rows x 18 columns]

In [33]:
#seperate x=independent(Symptom_1	Symptom_2	Symptom_3	Symptom_4	Symptom_5	Symptom_6	Symptom_7	Symptom_8	Symptom_9	Symptom_10
#Symptom_11	Symptom_12	Symptom_13	Symptom_14	Symptom_15	Symptom_16	Symptom_17) and y=dependent(Disease)
x=dataset[["Symptom_1",	"Symptom_2","Symptom_3","Symptom_4","Symptom_5","Symptom_6","Symptom_7","Symptom_8","Symptom_9","Symptom_10","Symptom_11","Symptom_12","Symptom_13","Symptom_14","Symptom_15","Symptom_16","Symptom_17"]].values
x

array([[33, 35, 35, ...,  3,  3,  1],
       [24, 27, 18, ...,  3,  3,  1],
       [33, 27, 18, ...,  3,  3,  1],
       ...,
       [ 4,  4, 22, ...,  3,  3,  1],
       [24, 20, 42, ...,  3,  3,  1],
       [24, 18,  4, ...,  3,  3,  1]], dtype=int64)

In [34]:
#seperate y=dependent('Diseases')
y=dataset['Disease'].values
y

array([15, 15, 15, ..., 38, 35, 27], dtype=int64)

In [37]:
#create train_test_split

from sklearn.model_selection import train_test_split

#test_train_data.... 
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)


In [38]:
len(x_train)

3936

In [40]:
len(x_test)

984

In [41]:
#create Random forest classifier model

from sklearn.ensemble import RandomForestClassifier

In [42]:
#create a instance of RandomForestClassifier

rfc=RandomForestClassifier()

In [43]:
rfc.fit(x_train,y_train)

RandomForestClassifier()

In [44]:
x_test

array([[11, 46, 39, ...,  3,  3,  1],
       [ 6, 15, 24, ...,  3,  3,  1],
       [15, 42, 21, ...,  3,  3,  1],
       ...,
       [11, 46, 39, ...,  3,  3,  1],
       [33, 15, 28, ...,  3,  3,  1],
       [11, 24, 52, ...,  3,  3,  1]], dtype=int64)

In [45]:
y_test

array([12, 34, 21, 28, 22, 38, 17, 25, 11,  7, 38, 21, 31, 34, 34,  3, 13,
       31,  4, 22, 36, 24, 27, 40,  3, 33,  3, 30, 24, 26,  0, 32, 10,  5,
       19,  7, 37, 13, 19, 22, 30, 38, 28, 10,  3, 35, 28, 12,  3, 15, 37,
        0, 35,  2,  3, 10, 34,  5, 26,  6, 16,  6, 30, 34,  7, 31, 24, 36,
       27, 30,  1,  1,  7,  7, 15, 16, 28,  9, 39, 24, 31, 34, 24,  3,  9,
       30,  9, 35,  9, 16,  3, 30, 32, 10, 14, 12, 30, 23, 15, 14, 23, 16,
       13, 38, 18, 11, 14, 15, 40,  0,  5,  3, 28, 12, 18, 40,  3, 31, 33,
       35,  3, 32, 38, 26,  1,  3,  5, 29,  8, 39, 33, 37, 27, 30, 37,  4,
        3,  7,  1, 19,  1,  8, 40, 23, 13, 30, 26,  0, 34,  4, 30,  3, 14,
        5, 28,  1, 15,  3, 24, 23, 15, 38, 31,  8,  2,  2,  4, 28, 14, 39,
       19, 14, 19, 33, 40, 12, 35, 11, 13, 37, 26, 21, 31, 18, 26, 14, 13,
       17, 40, 11, 21, 26, 38, 14, 34, 35, 26, 22, 33,  2,  9, 33, 13, 25,
       17, 37, 28, 13, 23, 39, 25, 35, 30, 13, 27, 35, 19,  4,  1, 40,  0,
       12, 14, 21, 15,  0

In [48]:
rfc.predict(x_test)

array([12, 34, 21, 28, 22, 38, 17, 25, 11,  7, 38, 21, 31, 34, 34,  3, 13,
       31,  4, 22, 36, 24, 27, 40,  3, 33,  3, 30, 24, 26,  0, 32, 10,  5,
       19,  7, 37, 13, 19, 22, 30, 38, 28, 10,  3, 35, 28, 12,  3, 15, 37,
        0, 35,  2,  3, 10, 34,  5, 26,  6, 16,  6, 30, 34,  7, 31, 24, 36,
       27, 30,  1,  1,  7,  7, 15, 16, 28,  9, 39, 24, 31, 34, 24,  3,  9,
       30,  9, 35,  9, 16,  3, 30, 32, 10, 14, 12, 30, 23, 15, 14, 23, 16,
       13, 38, 18, 11, 14, 15, 40,  0,  5,  3, 28, 12, 18, 40,  3, 31, 33,
       35,  3, 32, 38, 26,  1,  3,  5, 29,  8, 39, 33, 37, 27, 30, 37,  4,
        3,  7,  1, 19,  1,  8, 40, 23, 13, 30, 26,  0, 34,  4, 30,  3, 14,
        5, 28,  1, 15,  3, 24, 23, 15, 38, 31,  8,  2,  2,  4, 28, 14, 39,
       19, 14, 19, 33, 40, 12, 35, 11, 13, 37, 26, 21, 31, 18, 26, 14, 13,
       17, 40, 11, 21, 26, 38, 14, 34, 35, 26, 22, 33,  2,  9, 33, 13, 25,
       17, 37, 28, 13, 23, 39, 25, 35, 30, 13, 27, 35, 19,  4,  1, 40,  0,
       12, 14, 21, 15,  0

In [51]:
rfc.predict([[33,35,35,11,38,32,26,21,22,21,18,11,8,4,3,3,1]])

array([15], dtype=int64)

In [52]:
rfc.predict([[32,350,5,1,33,39,6,1,2,2,1,1,3,4,6,7,1]])

array([26], dtype=int64)

In [53]:
rfc.score(x_test,y_test)

1.0

In [54]:
#now we can find out least important feature with rfc.feature_importances_

imp_features=pd.Series(rfc.feature_importances_,index=["Symptom_1",	"Symptom_2","Symptom_3","Symptom_4","Symptom_5","Symptom_6","Symptom_7","Symptom_8","Symptom_9","Symptom_10","Symptom_11","Symptom_12","Symptom_13","Symptom_14","Symptom_15","Symptom_16","Symptom_17"])

In [55]:
imp_features.sort_values()

Symptom_17    0.000000
Symptom_16    0.001457
Symptom_14    0.010291
Symptom_15    0.012259
Symptom_13    0.012343
Symptom_12    0.022154
Symptom_11    0.022729
Symptom_10    0.027743
Symptom_9     0.032220
Symptom_8     0.034236
Symptom_7     0.052860
Symptom_6     0.056855
Symptom_5     0.088699
Symptom_4     0.121843
Symptom_3     0.152665
Symptom_2     0.167181
Symptom_1     0.184466
dtype: float64

In [ ]:
#new RandomForest model with symptom_17